{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "0ba80339-131e-4566-af32-357ff9251dd7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "----- SUMMARY -----\n",
      "Here is a summary of the text in 5 simple bullet points:\n",
      "\n",
      "• Artificial Intelligence (AI) is changing the way businesses work by automating certain tasks.\n",
      "• This helps companies be more efficient and productive.\n",
      "• AI also allows businesses to make better decisions based on data, rather than just relying on intuition or experience.\n",
      "• Companies are using AI for customer service, which means they can respond quickly and effectively to customers' needs.\n",
      "• AI is also being used for things like predicting what customers will want and personalizing their experiences with a company.\n"
     ]
    }
   ],
   "source": [
    "# Import required libraries\n",
    "from langchain_community.llms import Ollama\n",
    "\n",
    "# Initialize Llama3 model via Ollama\n",
    "llm = Ollama(model=\"llama3\")\n",
    "\n",
    "# -------------------------------\n",
    "# 1. SUMMARIZATION FUNCTION\n",
    "# -------------------------------\n",
    "def summarize_text(text):\n",
    "    prompt = f\"\"\"\n",
    "    You are an expert summarizer.\n",
    "    Summarize the following text in 5 bullet points in simple language.\n",
    "\n",
    "    Text:\n",
    "    {text}\n",
    "    \"\"\"\n",
    "    return llm.invoke(prompt)\n",
    "\n",
    "text_data = \"\"\"\n",
    "Artificial Intelligence is transforming industries by automating tasks,\n",
    "improving efficiency, and enabling data-driven decision making.\n",
    "Companies are using AI for customer service, predictive analytics,\n",
    "and personalization.\n",
    "\"\"\"\n",
    "\n",
    "print(\"----- SUMMARY -----\")\n",
    "print(summarize_text(text_data))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "0e98eb38-4a5c-412c-be4e-c6d42839ef30",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "----- SENTIMENT -----\n",
      "Positive\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# -------------------------------\n",
    "# 2. SENTIMENT ANALYSIS FUNCTION\n",
    "# -------------------------------\n",
    "def analyze_sentiment(text):\n",
    "    prompt = f\"\"\"\n",
    "    Analyze the sentiment of the following text.\n",
    "    Return only one word: Positive, Negative, or Neutral.\n",
    "\n",
    "    Text:\n",
    "    {text}\n",
    "    \"\"\"\n",
    "    return llm.invoke(prompt)\n",
    "\n",
    "\n",
    "text_data = \"\"\"\n",
    "Artificial Intelligence is great \n",
    "\"\"\"\n",
    "\n",
    "\n",
    "print(\"\\n----- SENTIMENT -----\")\n",
    "print(analyze_sentiment(text_data))\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "3ae09097-f850-45be-96c6-bdb07f58df8f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "----- Q&A -----\n",
      "According to the context, yes, India is a democratic country. It is stated that \"India is the world's largest democracy\" and that it operates as a federal republic with 28 states and 8 union territories. Additionally, the Constitution of India is described as the supreme law, ensuring fundamental rights, which further supports the notion that India is a democratic country.\n"
     ]
    }
   ],
   "source": [
    "def ask_question(context, question):\n",
    "    prompt = f\"\"\"\n",
    "    Answer the question based on the context.\n",
    "\n",
    "    Context:\n",
    "    {context}\n",
    "\n",
    "    Question:\n",
    "    {question}\n",
    "    \"\"\"\n",
    "    return llm.invoke(prompt)\n",
    "\n",
    "\n",
    "# -------------------------------\n",
    "# SAMPLE INPUT\n",
    "# -------------------------------\n",
    "text_data = \"\"\"\n",
    "India, officially the Republic of India, is a vast, democratic country in South Asia, known for its incredible diversity in culture, language, and geography, spanning from the Himalayas to the Indian Ocean. As the world's seventh-largest nation by area and second-most populous, it represents a rich, ancient civilization that became independent on August 15, 1947. India is a secular state, fostering harmony among diverse religions, including Hinduism, Islam, Christianity, Sikhism, Buddhism, and Jainism. \n",
    "BYJU'S\n",
    "BYJU'S\n",
    " +4\n",
    "India is a South Asian nation, bordered by Pakistan, China, Nepal, Bhutan, Bangladesh, and Myanmar.\n",
    "It is the seventh-largest country by area, encompassing diverse climates and landscapes.\n",
    "India is the second-most populous country in the world.\n",
    "The country has a rich history dating back to ancient times, including the Indus Valley Civilization.\n",
    "India achieved independence from British rule on August 15, 1947.\n",
    "The national capital is New Delhi, a historic and political hub.\n",
    "India is the world's largest democracy.\n",
    "It operates as a federal republic with 28 states and 8 union territories.\n",
    "The Constitution of India is the supreme law, ensuring fundamental rights.\n",
    "The nation is a land of many festivals, such as Diwali, Holi, and Eid.\n",
    "India is known for its \"unity in diversity,\" with numerous languages spoken.\n",
    "Hindi and English are the official languages, but hundreds of languages exist.\n",
    "The country has a vibrant culture with traditional music, dance, and arts.\n",
    "Indian food is diverse and famous worldwide for its use of spices.\n",
    "The Himalayas in the north act as a natural barrier and a source of major rivers.\n",
    "The Ganges, Yamuna, Brahmaputra, and Narmada are major, sacred rivers.\n",
    "India is surrounded by the Bay of Bengal, the Arabian Sea, and the Indian Ocean.\n",
    "Agriculture is a major profession, with farmers contributing significantly to the economy.\n",
    "Mahatma Gandhi is recognized as the Father of the Nation, leading the independence movement.\n",
    "The national flag is the Tiranga, featuring saffron, white, green, and the Ashoka Chakra.\n",
    "The Lion Capital of Ashoka is the official national emblem.\n",
    "India is a fast-growing, major economy (G20) with a rapidly expanding middle class.\n",
    "The country is a hub for information technology and software services.\n",
    "India has a strong space research program (ISRO), achieving major milestones.\n",
    "It is a nuclear-weapon state with a large, strong military.\n",
    "The Param Vir Chakra is the highest military decoration.\n",
    "The country has a rich tradition of spirituality and is the birthplace of Yoga.\n",
    "Bollywood, the Mumbai-based film industry, is one of the largest in the world.\n",
    "India has four biodiversity hotspots and a rich variety of wildlife.\n",
    "The Thar Desert is located in the northwestern part of the country.\n",
    "Traditional dressing includes sarees, salwar kameez, and kurta-pyjamas.\n",
    "The country faces challenges like poverty, gender inequality, and environmental pollution.\n",
    "Education is a focus, with growing literacy rates across the country.\n",
    "India is a significant player in global politics and international relations.\n",
    "The country has a vibrant democracy with frequent elections.\n",
    "Tourism is a booming industry, featuring landmarks like the Taj Mahal.\n",
    "Ayurveda, a traditional medical system, originated in India.\n",
    "The country is known for its hospitality, summarized by \"Atithi Devo Bhava\".\n",
    "India has a diverse sports culture, with cricket being immensely popular.\n",
    "The country has made significant contributions to literature, art, and science.\n",
    "Many, great philosophers, scientists, and leaders like APJ Abdul Kalam have emerged from India.\n",
    "\"\"\"\n",
    "\n",
    "\n",
    "\n",
    "print(\"\\n----- Q&A -----\")\n",
    "print(ask_question(text_data, \"is india a democratic country?\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "924c801e-09fc-4348-b53b-9461c5848ba5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting langchain==0.1.17\n",
      "  Downloading langchain-0.1.17-py3-none-any.whl.metadata (13 kB)\n",
      "Requirement already satisfied: langchain-community in c:\\users\\shale\\anaconda3\\lib\\site-packages (0.4.1)\n",
      "Requirement already satisfied: PyYAML>=5.3 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (6.0.1)\n",
      "Requirement already satisfied: SQLAlchemy<3,>=1.4 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (2.0.34)\n",
      "Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (3.10.5)\n",
      "Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (0.6.7)\n",
      "Requirement already satisfied: jsonpatch<2.0,>=1.33 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (1.33)\n",
      "Collecting langchain-community\n",
      "  Downloading langchain_community-0.0.38-py3-none-any.whl.metadata (8.7 kB)\n",
      "Collecting langchain-core<0.2.0,>=0.1.48 (from langchain==0.1.17)\n",
      "  Downloading langchain_core-0.1.53-py3-none-any.whl.metadata (5.9 kB)\n",
      "Collecting langchain-text-splitters<0.1,>=0.0.1 (from langchain==0.1.17)\n",
      "  Downloading langchain_text_splitters-0.0.2-py3-none-any.whl.metadata (2.2 kB)\n",
      "Collecting langsmith<0.2.0,>=0.1.17 (from langchain==0.1.17)\n",
      "  Downloading langsmith-0.1.147-py3-none-any.whl.metadata (14 kB)\n",
      "Requirement already satisfied: numpy<2,>=1 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (1.26.4)\n",
      "Requirement already satisfied: pydantic<3,>=1 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (2.12.5)\n",
      "Requirement already satisfied: requests<3,>=2 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (2.33.1)\n",
      "Requirement already satisfied: tenacity<9.0.0,>=8.1.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (8.2.3)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.17) (2.4.0)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.17) (1.2.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.17) (24.3.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.17) (1.4.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.17) (6.0.4)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.17) (1.11.0)\n",
      "Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from dataclasses-json<0.7,>=0.5.7->langchain==0.1.17) (3.26.2)\n",
      "Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from dataclasses-json<0.7,>=0.5.7->langchain==0.1.17) (0.9.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from jsonpatch<2.0,>=1.33->langchain==0.1.17) (2.1)\n",
      "Collecting packaging<24.0,>=23.2 (from langchain-core<0.2.0,>=0.1.48->langchain==0.1.17)\n",
      "  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langsmith<0.2.0,>=0.1.17->langchain==0.1.17) (0.28.1)\n",
      "Requirement already satisfied: orjson<4.0.0,>=3.9.14 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langsmith<0.2.0,>=0.1.17->langchain==0.1.17) (3.11.8)\n",
      "Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langsmith<0.2.0,>=0.1.17->langchain==0.1.17) (1.0.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from pydantic<3,>=1->langchain==0.1.17) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from pydantic<3,>=1->langchain==0.1.17) (2.41.5)\n",
      "Requirement already satisfied: typing-extensions>=4.14.1 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from pydantic<3,>=1->langchain==0.1.17) (4.15.0)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from pydantic<3,>=1->langchain==0.1.17) (0.4.2)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from requests<3,>=2->langchain==0.1.17) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from requests<3,>=2->langchain==0.1.17) (2.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.26 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from requests<3,>=2->langchain==0.1.17) (2.2.3)\n",
      "Requirement already satisfied: certifi>=2023.5.7 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from requests<3,>=2->langchain==0.1.17) (2025.6.15)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from SQLAlchemy<3,>=1.4->langchain==0.1.17) (3.0.1)\n",
      "Requirement already satisfied: anyio in c:\\users\\shale\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain==0.1.17) (4.2.0)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\shale\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain==0.1.17) (1.0.9)\n",
      "Requirement already satisfied: h11>=0.16 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain==0.1.17) (0.16.0)\n",
      "Requirement already satisfied: mypy-extensions>=0.3.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain==0.1.17) (1.0.0)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from anyio->httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain==0.1.17) (1.3.0)\n",
      "Downloading langchain-0.1.17-py3-none-any.whl (867 kB)\n",
      "   ---------------------------------------- 0.0/867.6 kB ? eta -:--:--\n",
      "   ------------------------ --------------- 524.3/867.6 kB 2.8 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 867.6/867.6 kB 3.0 MB/s eta 0:00:00\n",
      "Downloading langchain_community-0.0.38-py3-none-any.whl (2.0 MB)\n",
      "   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--\n",
      "   --------------- ------------------------ 0.8/2.0 MB 4.2 MB/s eta 0:00:01\n",
      "   ------------------------------- -------- 1.6/2.0 MB 4.7 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 2.0/2.0 MB 4.5 MB/s eta 0:00:00\n",
      "Downloading langchain_core-0.1.53-py3-none-any.whl (303 kB)\n",
      "Downloading langchain_text_splitters-0.0.2-py3-none-any.whl (23 kB)\n",
      "Downloading langsmith-0.1.147-py3-none-any.whl (311 kB)\n",
      "Downloading packaging-23.2-py3-none-any.whl (53 kB)\n",
      "Installing collected packages: packaging, langsmith, langchain-core, langchain-text-splitters, langchain-community, langchain\n",
      "  Attempting uninstall: packaging\n",
      "    Found existing installation: packaging 24.1\n",
      "    Uninstalling packaging-24.1:\n",
      "      Successfully uninstalled packaging-24.1\n",
      "  Attempting uninstall: langsmith\n",
      "    Found existing installation: langsmith 0.7.30\n",
      "    Uninstalling langsmith-0.7.30:\n",
      "      Successfully uninstalled langsmith-0.7.30\n",
      "  Attempting uninstall: langchain-core\n",
      "    Found existing installation: langchain-core 1.2.28\n",
      "    Uninstalling langchain-core-1.2.28:\n",
      "      Successfully uninstalled langchain-core-1.2.28\n",
      "  Attempting uninstall: langchain-text-splitters\n",
      "    Found existing installation: langchain-text-splitters 1.1.1\n",
      "    Uninstalling langchain-text-splitters-1.1.1:\n",
      "      Successfully uninstalled langchain-text-splitters-1.1.1\n",
      "  Attempting uninstall: langchain-community\n",
      "    Found existing installation: langchain-community 0.4.1\n",
      "    Uninstalling langchain-community-0.4.1:\n",
      "      Successfully uninstalled langchain-community-0.4.1\n",
      "Successfully installed langchain-0.1.17 langchain-community-0.0.38 langchain-core-0.1.53 langchain-text-splitters-0.0.2 langsmith-0.1.147 packaging-23.2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
      "langchain-classic 1.0.3 requires langchain-core<2.0.0,>=1.2.19, but you have langchain-core 0.1.53 which is incompatible.\n",
      "langchain-classic 1.0.3 requires langchain-text-splitters<2.0.0,>=1.1.1, but you have langchain-text-splitters 0.0.2 which is incompatible.\n",
      "langchain-experimental 0.4.1 requires langchain-community<1.0.0,>=0.4.0, but you have langchain-community 0.0.38 which is incompatible.\n",
      "langchain-experimental 0.4.1 requires langchain-core<2.0.0,>=1.0.0, but you have langchain-core 0.1.53 which is incompatible.\n",
      "langchain-ollama 1.1.0 requires langchain-core<2.0.0,>=1.2.21, but you have langchain-core 0.1.53 which is incompatible.\n",
      "langgraph-checkpoint 4.0.1 requires langchain-core>=0.2.38, but you have langchain-core 0.1.53 which is incompatible.\n",
      "langgraph-prebuilt 1.0.9 requires langchain-core>=1.0.0, but you have langchain-core 0.1.53 which is incompatible.\n",
      "thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: langchain==0.1.17 in c:\\users\\shale\\anaconda3\\lib\\site-packages (0.1.17)\n",
      "Requirement already satisfied: langchain-community in c:\\users\\shale\\anaconda3\\lib\\site-packages (0.0.38)\n",
      "Requirement already satisfied: PyYAML>=5.3 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (6.0.1)\n",
      "Requirement already satisfied: SQLAlchemy<3,>=1.4 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (2.0.34)\n",
      "Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (3.10.5)\n",
      "Requirement already satisfied: dataclasses-json<0.7,>=0.5.7 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (0.6.7)\n",
      "Requirement already satisfied: jsonpatch<2.0,>=1.33 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (1.33)\n",
      "Requirement already satisfied: langchain-core<0.2.0,>=0.1.48 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (0.1.53)\n",
      "Requirement already satisfied: langchain-text-splitters<0.1,>=0.0.1 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (0.0.2)\n",
      "Requirement already satisfied: langsmith<0.2.0,>=0.1.17 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (0.1.147)\n",
      "Requirement already satisfied: numpy<2,>=1 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (1.26.4)\n",
      "Requirement already satisfied: pydantic<3,>=1 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (2.12.5)\n",
      "Requirement already satisfied: requests<3,>=2 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (2.33.1)\n",
      "Requirement already satisfied: tenacity<9.0.0,>=8.1.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain==0.1.17) (8.2.3)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.17) (2.4.0)\n",
      "Requirement already satisfied: aiosignal>=1.1.2 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.17) (1.2.0)\n",
      "Requirement already satisfied: attrs>=17.3.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.17) (24.3.0)\n",
      "Requirement already satisfied: frozenlist>=1.1.1 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.17) (1.4.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.17) (6.0.4)\n",
      "Requirement already satisfied: yarl<2.0,>=1.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain==0.1.17) (1.11.0)\n",
      "Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from dataclasses-json<0.7,>=0.5.7->langchain==0.1.17) (3.26.2)\n",
      "Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from dataclasses-json<0.7,>=0.5.7->langchain==0.1.17) (0.9.0)\n",
      "Requirement already satisfied: jsonpointer>=1.9 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from jsonpatch<2.0,>=1.33->langchain==0.1.17) (2.1)\n",
      "Requirement already satisfied: packaging<24.0,>=23.2 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langchain-core<0.2.0,>=0.1.48->langchain==0.1.17) (23.2)\n",
      "Requirement already satisfied: httpx<1,>=0.23.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langsmith<0.2.0,>=0.1.17->langchain==0.1.17) (0.28.1)\n",
      "Requirement already satisfied: orjson<4.0.0,>=3.9.14 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langsmith<0.2.0,>=0.1.17->langchain==0.1.17) (3.11.8)\n",
      "Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from langsmith<0.2.0,>=0.1.17->langchain==0.1.17) (1.0.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from pydantic<3,>=1->langchain==0.1.17) (0.6.0)\n",
      "Requirement already satisfied: pydantic-core==2.41.5 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from pydantic<3,>=1->langchain==0.1.17) (2.41.5)\n",
      "Requirement already satisfied: typing-extensions>=4.14.1 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from pydantic<3,>=1->langchain==0.1.17) (4.15.0)\n",
      "Requirement already satisfied: typing-inspection>=0.4.2 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from pydantic<3,>=1->langchain==0.1.17) (0.4.2)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from requests<3,>=2->langchain==0.1.17) (3.3.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from requests<3,>=2->langchain==0.1.17) (2.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.26 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from requests<3,>=2->langchain==0.1.17) (2.2.3)\n",
      "Requirement already satisfied: certifi>=2023.5.7 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from requests<3,>=2->langchain==0.1.17) (2025.6.15)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from SQLAlchemy<3,>=1.4->langchain==0.1.17) (3.0.1)\n",
      "Requirement already satisfied: anyio in c:\\users\\shale\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain==0.1.17) (4.2.0)\n",
      "Requirement already satisfied: httpcore==1.* in c:\\users\\shale\\anaconda3\\lib\\site-packages (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain==0.1.17) (1.0.9)\n",
      "Requirement already satisfied: h11>=0.16 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain==0.1.17) (0.16.0)\n",
      "Requirement already satisfied: mypy-extensions>=0.3.0 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7,>=0.5.7->langchain==0.1.17) (1.0.0)\n",
      "Requirement already satisfied: sniffio>=1.1 in c:\\users\\shale\\anaconda3\\lib\\site-packages (from anyio->httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain==0.1.17) (1.3.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install langchain==0.1.17 langchain-community"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "04a9e6ac-f39a-4c82-9e14-0985006416e5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Nice to meet you, Shalini! I'm delighted to be chatting with you today. My systems indicate that we are currently communicating via a web-based interface on your personal computer, specifically using the Google Chrome browser version 89.0.4389.82. As for myself, I'm an advanced language model trained on a vast corpus of text data, which includes but is not limited to books, articles, research papers, and online content. My training data spans multiple domains, including but not limited to science, history, technology, literature, and more. I'm constantly learning and improving my responses based on the conversations I have with users like you! What would you like to talk about, Shalini?\n"
     ]
    }
   ],
   "source": [
    "from langchain_community.llms import Ollama\n",
    "from langchain.memory import ConversationBufferMemory\n",
    "from langchain.chains import ConversationChain\n",
    "\n",
    "llm = Ollama(model=\"llama3\")\n",
    "\n",
    "memory = ConversationBufferMemory()\n",
    "\n",
    "conversation = ConversationChain(\n",
    "    llm=llm,\n",
    "    memory=memory\n",
    ")\n",
    "\n",
    "print(conversation.predict(input=\"Hi, my name is Shalini\"))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "c759b60b-dac2-43e1-ad92-dbe9a3605158",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Shalini! You just told me your name! I remember it clearly because I'm designed to process and retain information from our conversation. In fact, according to my internal memory logs, you introduced yourself as \"Shalini\" right at the beginning of our chat. Would you like to know more about the vast range of topics we can discuss or perhaps explore a specific area that interests you?\n"
     ]
    }
   ],
   "source": [
    "print(conversation.predict(input=\"What is my name?\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "58cf73ec-04f5-4557-9aa8-d918b06918b0",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4b09d92d-0303-42f3-be9e-c13ab715a980",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
